# Generated by Django 3.2.4 on 2021-06-06 00:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=40)),
                ('apellidos', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]*$', 'Solo carácteres alfanuméricos son permitidos.'), django.core.validators.MinLengthValidator(6, 'Debe de ingresar al menos 6 caracteres')])),
                ('comentario', models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]*$', 'Solo carácteres alfanuméricos son permitidos.')])),
                ('valoracion', models.IntegerField(choices=[('Negativo', -2), ('Positivo', 1)])),
                ('id_estrella', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.estrella')),
            ],
        ),
    ]
