# Generated by Django 3.2.4 on 2021-06-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nickname',
        ),
    ]
