# Generated by Django 3.2.4 on 2021-06-06 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comentario_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nickname',
            field=models.CharField(default='', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z]*$', 'Solo carácteres alfanuméricos son permitidos.'), django.core.validators.MinValueValidator(6, 'Debe de ingresar al menos 6 caracteres')]),
        ),
    ]
