# Generated by Django 3.2.4 on 2021-06-06 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comentario_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z*]+$', 'Solo carácteres alfanuméricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nickname',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z*]+$', 'Solo carácteres alfanuméricos son permitidos.')]),
        ),
    ]
