# Generated by Django 3.2.4 on 2021-06-06 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210606_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[0-9\\da-z\\dA-Z*]+$', 'Solo carácteres alfanuméricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nickname',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9\\da-z\\dA-Z*]+$', 'Solo carácteres alfanuméricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='valoracion',
            field=models.IntegerField(choices=[(-2, 'Negativo'), (1, 'Positivo')]),
        ),
    ]
