# Generated by Django 3.2.4 on 2021-06-06 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210606_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-z\\d\\-_\\s]+$', 'Solo carácteres alfanuméricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nickname',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-z\\d\\-_\\s]+$', 'Solo carácteres alfanuméricos son permitidos.'), django.core.validators.RegexValidator('^[0-9A-Za-z]{6,}$', 'Debde ingresar almenos 6 caracteres.')]),
        ),
    ]
