# Generated by Django 3.2.4 on 2021-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210606_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
