# Generated by Django 3.2.4 on 2021-06-07 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210606_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\d\\-_\\s]+$', 'Solo carácteres alfanuméricos son permitidos.')]),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nickname',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\d\\-_\\s]+$', 'Solo carácteres alfanuméricos son permitidos.'), django.core.validators.RegexValidator('^[0-9A-Za-z]{6,}$', 'Dede ingresar al menos 6 caracteres.')]),
        ),
    ]
