# Generated by Django 3.2.4 on 2021-06-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comentario_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='color',
            field=models.CharField(choices=[('red', 'rojo'), ('blue', 'Azul')], default='rojo', max_length=4),
        ),
    ]
