# Generated by Django 3.2.4 on 2021-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_comentario_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='valoracion',
            field=models.IntegerField(choices=[(-1, 'Negativo'), (2, 'Positivo')]),
        ),
    ]
